version: 2
updates:
  # JS / TS dependencies (pnpm monorepo)
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/apps/web"
      - "/packages/ui"
      - "/packages/eslint-config"
      - "/packages/typescript-config"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "08:00"
      timezone: "America/Bogota"
    open-pull-requests-limit: 5

    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

    groups:
      prod-deps:
        dependency-type: "production"
      dev-deps:
        dependency-type: "development"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "11:30"
      timezone: "America/Bogota"
    open-pull-requests-limit: 2
    groups:
      actions:
        patterns: ["*"]
